Repository Hyunminmax/Pollloop, pull requests merged in 2025-01, with the labels that each got.

#14 Feat/models4
  form/migrations/0001_initial.py
  form/migrations/0002_initial.py
  form/migrations/0003_respondent_is_complete.py
  form/migrations/0004_optionsofquestions_option_number.py
  form/models.py
  user/migrations/0001_initial.py
  user/models.py
Labels: update

#16 Feat/form002-1
  config/urls.py
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#19 swagger basic setting
  config/settings.py
  config/urls.py
Labels: enhancement

#21 feat/for002-2
  form/serializers.py
  form/views.py
Labels: enhancement

#22 hotfix:django-seed, psycopg2 삭제
  poetry.lock
  pyproject.toml
Labels: bug, update

#23 Feat/settings
  config/settings_base.py
  config/settings_local.py
  config/settings_prod.py
Labels: enhancement, update

#24 fix:문제의 보기가 반환되지 않던 이슈 해결
  form/serializers.py
Labels: fixed

#27 refactor:swagger 예문추가
  form/views.py
Labels: documentation

#31 feat:폼 참여정보 업데이트
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#32 fix:DEFAULT_AUTHENTICATION_CLASSES
  config/settings_base.py
Labels: fixed

#33 Update README.md
  README.md
Labels: documentation

#34 refactor:get_object_or_404 적용
  form/serializers.py
Labels: update

#35 hotfix:import get_object_or_404
  form/serializers.py
Labels: fixed

#37 user, form model 수정, user ID값 email로 변경 -> +로직 수정
  form/models.py
  user/models.py
  user/urls.py
  user/views.py
Labels: update, fixed

#38 username error 수정
  user/models.py
Labels: fixed

#39 add migrations
  form/migrations/0003_form_is_bookmark_form_is_private_form_target_count_and_more.py
  user/migrations/0002_alter_customuser_options_alter_customuser_managers_and_more.py
Labels: documentation, update

#41 feat/for010
  config/urls.py
  form/migrations/0004_rename_options_of_question_multipleanswers_options_of_questions.py
  form/migrations/0005_rename_options_of_questions_multipleanswers_options_of_question.py
  form/serializers.py
  form/urls.py
  form/views.py
Labels: fixed

#42 feat/for002-2
  form/migrations/0006_alter_optionsofquestions_option_context.py
  form/models.py
  form/views.py
Labels: documentation, fixed

#43 Feat/for002 2
  form/migrations/0007_alter_optionsofquestions_option_number.py
  form/models.py
  form/serializers.py
Labels: documentation, fixed

#44 feat/for010
  form/serializers.py
Labels: fixed

#46 Feat/for003
  form/serializers.py
Labels: enhancement

#48 Feat/for004
  form/serializers.py
  form/urls.py
  form/views.py
Labels: documentation

#49 feat:modelupdate
  form/serializers.py
  form/views.py
Labels: update

#53 Feature/user
  config/settings_base.py
  poetry.lock
  pyproject.toml
  user/serializers.py
  user/urls.py
  user/views.py
Labels: enhancement

#54 feat/for008
  form/serializers.py
  form/urls.py
  form/views.py
Labels: documentation

#55 feat/for004
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#57 Feat/for010
  form/migrations/0001_initial.py
  form/migrations/0002_initial.py
  form/migrations/0003_form_is_bookmark_form_is_private_form_target_count_and_more.py
  form/migrations/0004_rename_options_of_question_multipleanswers_options_of_questions.py
  form/migrations/0005_rename_options_of_questions_multipleanswers_options_of_question.py
  form/migrations/0006_alter_optionsofquestions_option_context.py
  form/migrations/0007_alter_optionsofquestions_option_number.py
  form/models.py
  form/serializers.py
  form/views.py
  user/migrations/0001_initial.py
  user/migrations/0002_alter_customuser_options_alter_customuser_managers_and_more.py
Labels: update, fixed

#59 /feat/for006
  form/serializers.py
Labels: update

#60 Feature/user
  poetry.lock
  user/migrations/0002_alter_customuser_options_alter_customuser_managers_and_more.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: update

#61 feat/for006 참여자 목록 조회
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#63 PUT, PATCH -> POST로 수정
  user/serializers.py
  user/views.py
Labels: fixed

#66 Kakao Social swagger-tag분리
  user/views.py
Labels: documentation

#67 feat/for006
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#72 feat/for009
  form/serializers.py
  form/urls.py
  form/views.py
Labels: enhancement

#77 Chore/aws s3
  .gitignore
  config/settings.py
  config/settings_base.py
  config/settings_prod.py
  poetry.lock
  pyproject.toml
Labels: update

#79 hotfix
  pyproject.toml
Labels: fixed

#84 chore EC2설정
  config/settings_prod.py
Labels: update

#86 hotfix/For002-2
  common/__init__.py
  common/admin.py
  common/apps.py
  common/migrations/__init__.py
  common/models.py
  common/tests.py
  common/views.py
  form/serializers.py
Labels: fixed

#101 Feat/com01
  common/serializers.py
  common/urls.py
  common/views.py
  config/settings_base.py
  config/urls.py
Labels: enhancement

#102 hotfix
  common/urls.py
  config/urls.py
Labels: update

#105 Feat/form002 1
  form/migrations/0003_alter_form_form_description_alter_form_tag.py
  form/models.py
Labels: fixed

#107 hotfix
  form/serializers.py
  form/views.py
Labels: fixed

#111 hotfix
  form/serializers.py
  form/views.py
Labels: fixed

#115 refactor
  common/serializers.py
  common/views.py
  user/views.py
Labels: update

#116 Create index.html
  index.html
Labels: documentation

#118 hotfix
  common/serializers.py
  common/views.py
Labels: update

#119 hotfix
  common/serializers.py
  common/views.py
Labels: update

#121 chore/SSL1
  config/settings_prod.py
Labels: update

#122 feat/for008
  form/serializers.py
Labels: update

#125 Feat/for007
  config/settings_base.py
  form/serializers.py
  form/views.py
Labels: enhancement, update

#126 feat/for002-3
  form/serializers.py
  form/views.py
Labels: enhancement, update

#129 style
  user/views.py
Labels: fixed

#130 fix
  user/serializers.py
Labels: update

#131 feat/mem001
  config/settings_base.py
Labels: update

#132 feat/closed
  form/serializers.py
Labels: enhancement, update

#133 style
  form/views.py
Labels: update

#134 이메일 비동기 대량발송 개발을 위한 사전준비
  common/views.py
  config/urls.py
Labels: enhancement
